### ISSUE TITLE
弱弱的问一句tcp连接支持使用代理吗

### ISSUE THREAD

**Issue by lovezm** [simon300000/bilibili-live-ws#12]
是否可以通过http或者socke代理来建立连接呢

**Comment by simon300000** [comment]
wuaaa 我也不知道呀
TCP的底层是 https://nodejs.org/api/net.html#net_class_net_socket
似乎不像http有个agent设置，想要实现代理的话可能需要自己写一点代码哦→_→

首先建立一个TCP Server，（通过http/socks代理）把连接进来的socket的包全都转发一遍，然后在代理的目的地再把包发给目标地址？
然后改host, port连接到那个TCP Server

类似：
LiveTCP --tcp--> 你的TCP代理 --tcp--> Bilibili
或者：
LiveTCP --tcp--> 本地TCP代理客户端 --(http/socks)--> 目标TCP代理服务端 --tcp--> Bilibili

简单的TCP Server大概这种感觉吧：
https://gist.github.com/kfox/2313683

**Comment by lovezm** [comment]
感谢 我去研究一下

**Comment by simon300000** [comment]
研究得怎么样啦？

**Comment by lovezm** [comment]
连接倒是可以 不算人气 放弃了 hhh

**Comment by simon300000** [comment]
wua
可惜
