### ISSUE TITLE
感谢大佬的inflate方法

### ISSUE THREAD

**Issue by Billyzou0741326** [simon300000/bilibili-live-ws#16]
弹幕proto_ver 2的inflate方法我卡了好久，一直没想到解压后的buffer也带有header... 看到这行才明白23333
https://github.com/simon300000/bilibili-live-ws/blob/824eb9f59541cfbf017849922881413939ff1f9e/src/buffer.js#L42
多谢simon大佬

**Comment by simon300000** [comment]
😀
