### ISSUE TITLE
[feature request] 允许使用房间短号

### ISSUE THREAD

**Issue by Discreater** [simon300000/bilibili-live-ws#172]
目前无法通过房间短号连接至直播间。
可以通过 `https://api.live.bilibili.com/room/v1/Room/mobileRoomInit?id=${room_id}` 根据 `room_id` （短号或实际房间号）获取房间信息，包括实际房间号。

**Comment by simon300000** [comment]
咦，我也不知道怎么使用短房间号连接，要不我把这个函数一起写进extra里面？

**Comment by simon300000** [comment]
写进去了，可以直接用

**Comment by simon300000** [comment]
大概没问题了ba
