### ISSUE TITLE
想请教下ts的问题

### ISSUE THREAD

**Issue by colorworlds** [simon300000/bilibili-live-ws#18]
请问这是什么语法啊？
```typescript
const keepLive = (Base: typeof LiveWS | typeof LiveTCP) => class extends EventEmitter{
    //...
}
```

**Comment by simon300000** [comment]
这是一个返回Class的function
写成js是这样

```javascript
const keepLive = Base => class extends EventEmitter {}
```

可以这样调用
```javascript
new (keepLive())()
```

**Comment by simon300000** [comment]
一个例子：
```javascript
const newJob = (jobName, income) => class {
  constructor(name) {
    this.name = name
  }
  makeMoney() {
    console.log(`我是${this.name}, 我的工作是${jobName}, 我今天赚了 ${income}¥!`)
  }
}

const Manager = newJob('高层管理', 20000)
const SmallManager = newJob('中层管理', 12000)

const simon = new Manager('Simon')
const dorothy = new SmallManager('Dorothy')

simon.makeMoney()
// 我是Simon, 我的工作是高层管理, 我今天赚了 20000¥!

dorothy.makeMoney()
// 我是Dorothy, 我的工作是中层管理, 我今天赚了 12000¥!

```

**Comment by colorworlds** [comment]
> 一个例子：
> 
> ```js
> const newJob = (jobName, income) => class {
>   constructor(name) {
>     this.name = name
>   }
>   makeMoney() {
>     console.log(`我是${this.name}, 我的工作是${jobName}, 我今天赚了 ${income}¥!`)
>   }
> }
> 
> const Manager = newJob('高层管理', 20000)
> const SmallManager = newJob('中层管理', 12000)
> 
> const simon = new Manager('Simon')
> const dorothy = new SmallManager('Dorothy')
> 
> simon.makeMoney()
> // 我是Simon, 我的工作是高层管理, 我今天赚了 20000¥!
> 
> dorothy.makeMoney()
> // 我是Dorothy, 我的工作是中层管理, 我今天赚了 12000¥!
> ```

谢谢大佬！受教了！

**Comment by simon300000** [comment]
不用谢www
