### ISSUE TITLE
浏览器环境下，使用 Vite 打包时出现错误

### ISSUE THREAD

**Issue by idlist** [simon300000/bilibili-live-ws#180]
出现了这个错误，会导致 JS 脚本无法继续加载。

![image](https://user-images.githubusercontent.com/29368226/141283694-97c4aa89-2f1b-42d4-9463-6641927a52ac.png)

这里有一个 [用来复现的迷你环境](https://github.com/idlist/issue-repros/tree/main/vite-with-bws)，`npm start` 后就可以在浏览器看见这个问题。目标是想办法让 `我加载出来了！` 出来（即打包成功）。

**Comment by simon300000** [comment]
试试看 bilibili-live-ws@6.0.2 😘

**Comment by idlist** [comment]
这个问题解决了，新的问题出现了……

![image](https://user-images.githubusercontent.com/29368226/142385665-ec4b18cf-dbd8-4869-a74b-40fa5f24f381.png)
![image](https://user-images.githubusercontent.com/29368226/142385712-f6834f4f-90f5-44c4-ab93-5b43414fc594.png)

应该是同源罢

**Comment by simon300000** [comment]
这个的确 getRoomid在浏览器环境的确不能用

**Comment by simon300000** [comment]
这是feature

**Comment by simon300000** [comment]
短房间号数量也不多 可以node环境打个表直接写死了

**Comment by idlist** [comment]
> 短房间号数量也不多 可以node环境打个表直接写死了

那不如axios之类的硬调API
不过既然是wontfix那我先关了 🤔
