### ISSUE TITLE
照着用其它语言做了个类似的实现，但是有时候发送心跳会突然断开连接

### ISSUE THREAD

**Issue by colorworlds** [simon300000/bilibili-live-ws#19]
遇到的情况就是有时候发送完心跳包后连接莫名其妙就断开了，也没有错误提示，直接就触发关闭，但相同的心跳包有时候就正常收到响应，排查了两天也不知道是哪里的问题，心跳包都是一样的，发送间隔的话，感觉因为有网络延迟，差几十毫秒应该也能接受，所以也排除了，第一次连接时发送的数据也都是对的，实在想不出问题出在哪，想问下大佬有没有什么头绪……

**Comment by simon300000** [comment]
是tcp还是ws？有没有更多信息？

**Comment by colorworlds** [comment]
> 是tcp还是ws？有没有更多信息？

ws，没有提示信息，观察发现断开可能发生在任何一次发出包之后，包括第一次请求房间的数据包发完就可能断开，但有时候就没事，大概数了下目前发心跳包最多不会超过20次，基本在二十次心跳包之中肯定就有哪次连接就断开了。
我是用godotscript这个游戏脚本语言实现的，我现在怀疑是不是这个语言提供的网络库本身有些设置问题……

**Comment by simon300000** [comment]
wua 有可能
大概需要用抓包来看看了→_→
