### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by YongAn404** [simon300000/bilibili-live-ws#236]
rm index.js index.d.ts browser.js browser.d.ts src/*.js src/*.d.ts;exit 0
'rm' 不是内部或外部命令，也不是可运行的程序
为什么会这样？

**Comment by simon300000** [comment]
哦哦 这个不用管他
这是用于删除残留文件的 有时文件不存在就会显示这个

**Comment by simon300000** [comment]
咦 不对 这是 linux 的程序 windows 没有 不用管他
