### ISSUE TITLE
关于 【Could not resolve "pako"】 与 【Dynamic require of "buffer" is not supported】的问题

### ISSUE THREAD

**Issue by LoveLoliii** [simon300000/bilibili-live-ws#266]
您好~
在[vite-react-electron](https://github.com/electron-vite/electron-vite-react)模板构建的一个electron项目中，
在渲染进程中使用``` import { LiveWS } from 'bilibili-live-ws/browser'```
运行提示：
```
X [ERROR] Could not resolve "pako"

    node_modules/bilibili-live-ws/src/inflate/browser.js:6:23:
      6 │ const pako_1 = require("pako");
```
之后我就``` yarn add pako ```
再次运行后
提示：
```
Uncaught Error: Dynamic require of "buffer" is not supported
    at chunk-ACCAMVX6.js?v=d5e4b460:12:9
    at node_modules/bilibili-live-ws/src/inflate/browser.js (browser.js:4:18)
    at __require2 (chunk-ACCAMVX6.js?v=d5e4b460:18:50)
    at node_modules/bilibili-live-ws/src/browser.js (browser.js:4:19)
    at __require2 (chunk-ACCAMVX6.js?v=d5e4b460:18:50)
    at node_modules/bilibili-live-ws/browser.js (browser.js:17:14)
    at __require2 (chunk-ACCAMVX6.js?v=d5e4b460:18:50)
    at dep:bilibili-live-ws_browser:1:16
```
browser.js 的第4行是这个：```const buffer_1 = require("buffer");```

**Comment by simon300000** [comment]
试试看yarn add buffer？

**Comment by LoveLoliii** [comment]
> 

还是同样的错误

**Comment by simon300000** [comment]
哎
试试bilibili-live-ws@6.2.1

**Comment by LoveLoliii** [comment]
> 哎 试试bilibili-live-ws@6.2.1

查了一圈 看起来像是vite pre-building 过程中的问题。 [这里看见的](https://zhuanlan.zhihu.com/p/399998544)。

**Comment by simon300000** [comment]
喔唷 那你解决了吗
还有一个办法是submodule然后直接作为ts import，ts代码应该是合格esm

**Comment by simon300000** [comment]
哦不 esm似乎要加上扩展名 可能还不行😵‍💫

**Comment by LoveLoliii** [comment]
> 哦不 esm似乎要加上扩展名 可能还不行😵‍💫

这块还不太懂 我去学学😀

**Comment by LoveLoliii** [comment]
> 喔唷 那你解决了吗 还有一个办法是submodule然后直接作为ts import，ts代码应该是合格esm

我悟了 我不在渲染进程用了  我去主进程用。

**Comment by simon300000** [comment]
没用过vite 你试试看👀

**Comment by LoveLoliii** [comment]
> 

在electron的主进程用 是没问题的![](https://s3.bmp.ovh/imgs/2022/05/30/9228a109fab96047.gif)

**Comment by simon300000** [comment]
太好啦！虽然有点可惜😭
