### ISSUE TITLE
KeepLive有遗留未关闭的连接

### ISSUE THREAD

**Issue by lhfy1990** [simon300000/bilibili-live-ws#28]
使用KeepLiveTCP时，发现接收到'close'后，原connection似乎并未关闭或销毁。
Node ver: 12.18.0
OS: Ubuntu 18
Handlers:
``` javascript
    this.on('open', () => {
       let ts = new Date();
       let output = `${ts.toISOString()}|Connected to room ${this.roomid}`;
       console.log(output);
       this.writeLog(output);
     });
 
     this.on('error', (e) => {
       let ts = new Date();
       let output = `${ts.toISOString()}|Connection got an error from room ${this.roomid}: ${e.message}`;
       console.log(output);
       this.writeLog(output);
     });
 
     this.on('close', () => {
       let ts = new Date();
       let output = `${ts.toISOString()}|Connection closed from room ${this.roomid}`;
       console.log(output);
       this.writeLog(output);
     });
 
     this.on('live', () => {
       this.on('heartbeat', (online) => {
         console.log(new Date(), online);
       });
    });
```

Log:
![Screenshot from 2020-06-04 16-37-49](https://user-images.githubusercontent.com/38107178/83770797-d0112d00-a681-11ea-86a1-b2a561b6cbb5.png)

**Comment by lhfy1990** [comment]
切换到`KeepLiveWS`检测到类似的情形。
![Screenshot from 2020-06-04 17-09-13](https://user-images.githubusercontent.com/38107178/83774534-1799b800-a686-11ea-8e2a-2d81afd11496.png)

**Comment by simon300000** [comment]
我去研究一下

**Comment by Billyzou0741326** [comment]
>      this.on('live', () => {
>        this.on('heartbeat', (online) => {
>          console.log(new Date(), online);
>        });
>      });

每当`live`事件触发时，添加一个`heartbeat`事件的回调。四次`live`的触发=4个`heartbeat`回调，意味着每次心跳输出4次

**Comment by Billyzou0741326** [comment]
连接本身应该是有正常关闭的

**Comment by lhfy1990** [comment]
@Billyzou0741326 谢谢，也就是说重连触发了新的`live`事件，心跳回调应当定义在`live`回调之外。我去试试。

**Comment by lhfy1990** [comment]
@simon300000 按照 @Billyzou0741326 所说的修改以后，不再生成额外的输出。Issue可以关闭了，谢谢各位。
重构代码示例：
```javascript
 this.on('heartbeat', (online) => {
   console.log(new Date(), online);
 });
 this.on('live', () => {
 });
```

**Comment by simon300000** [comment]
谢谢@Billyzou0741326 这几天我也有点忙没来得及看，问题解决了就是最好的哈哈
