### ISSUE TITLE
报错：KeepLiveTCP is not a constructor

### ISSUE THREAD

**Issue by tingshuai** [simon300000/bilibili-live-ws#304]
### RT:使用KeepLiveTCP 时报错，使用KeepLiveWS时正常

**主要环境：**

- win10
- Google chrome 版本 98.0.4750.0（正式版本）dev （64 位）
- node 12.16.2
- vue-cli 4
- vue 2.6.11
- bilibili-live-ws 6.2.1

**报错截图：**
![1661399770815](https://user-images.githubusercontent.com/23158246/186571294-91d3ba5f-fe78-4126-9d6d-81b888aa6e6f.png)

**相关代码：**
```
  const { KeepLiveWS, KeepLiveTCP } = require("bilibili-live-ws");
  const live = new KeepLiveTCP(176190);
  live.on("open", () => console.log("Connection is established"));
  live.on("live", () => {
    live.on("msg", (e) => {
      console.log(e);
    });
  });
```
**分别打印了下KeepLiveTCP，KeepLiveWS, 结果：**
![1661401962704](https://user-images.githubusercontent.com/23158246/186575783-ada14695-3e22-493e-9579-079dd2a04e7b.png)

**Comment by simon300000** [comment]
看起来是浏览器版本，确实会这样，目前TCP是不能在浏览器环境使用的，这是浏览器的限制

**Comment by tingshuai** [comment]
> 看起来是浏览器版本，确实会这样，目前TCP是不能在浏览器环境使用的，这是浏览器的限制

喔，好滴

**Comment by simon300000** [comment]
应该木有别的问题了吧（

**Comment by tingshuai** [comment]
> 应该木有别的问题了吧（
嗯 ，谢了
