### ISSUE TITLE
mobileRoomInit（短号解析接口）报404

### ISSUE THREAD

**Issue by Akarinnnnn** [simon300000/bilibili-live-ws#308]
是我被封了还是真的删了

**Comment by simon300000** [comment]
啊这 我检查一下

**Comment by simon300000** [comment]
啊，这。。。我这是正常的，是不是被封了？
（被封应该是412呀）

**Comment by Akarinnnnn** [comment]
确定了，是被封1天




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 上午8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [simon300000/bilibili-live-ws] mobileRoomInit（短号解析接口）报404 (Issue #308)





 
啊，这。。。我这是正常的，是不是被封了？
 （被封应该是412呀）
 
&mdash;

**Comment by Akarinnnnn** [comment]
应该是一小时内访问次数太多导致的（当时5分钟调用一次api）

**Comment by simon300000** [comment]
五分钟一次就会被封吗 这个力度有点大

其实短号就那么多，有需求的话可以拿浏览器打个表

**Comment by Akarinnnnn** [comment]
当时我在调试[解析库](https://github.com/Akarinnnnn/DanmakuR)，出错了经常重启，大部分重启间隔1分钟左右。刚开始没开短号解析，发现getDanmuInfo那得到第一个host经常拒绝连接。一开始没在意，也就把原来按顺序选host的算法改成随机。到后面调其它api才意识到被封了

**Comment by simon300000** [comment]
啊 这确实 你觉得我应该把host改成随机吗？

**Comment by Akarinnnnn** [comment]
host前两个是分流节点（也许叫CDN），第三个是默认地址。建议前两个连不上时再连第三个。

**Comment by Akarinnnnn** [comment]
原来是URL抄错了

**Comment by simon300000** [comment]
抄错了草
