### ISSUE TITLE
代码报错.提示未定义

### ISSUE THREAD

**Issue by daofeng2015** [simon300000/bilibili-live-ws#35]
![QQ截图20200706212520](https://user-images.githubusercontent.com/14891398/86598176-54cbcf80-bfcf-11ea-9da1-fe47908877c2.png)
...突然提示这个错误

**Comment by simon300000** [comment]
我发了新版本5.0.1，可以试试看有没有修复这个问题

**Comment by daofeng2015** [comment]
> 我发了新版本5.0.1，可以试试看有没有修复这个问题

修复了.....没有问题了
