### ISSUE TITLE
type为DANMU_MSG的信息里，用户名变成了****，uid和灯牌信息都变成了0

### ISSUE THREAD

**Issue by leonard2z** [simon300000/bilibili-live-ws#396]
数据如下：
{
  cmd: 'DANMU_MSG',
  info: [
    [
      0,             1,
      25,            16777215,
      1688137738344, -1938799775,
      0,             'e040a292',
      0,             0,
      0,             '',
      0,             '{}',
      '{}',          [Object],
      [Object],      0
    ],
    '打雷',
    [ 0, '折***', 0, 0, 0, 10000, 1, '' ],
    [],
    [ 0, 0, 9868950, '>50000', 0 ],
    [ '', '' ],
    0,
    0,
    null,
    { ts: 1688137738, ct: 'A7DACCD7' },
    0,
    0,
    null,
    null,
    0,
    7,
    [ 0 ]
  ],
  dm_v2: 'CiI0NDdjZjdjMmM0ODA2M2UzNjE5M2JjNWFmMDY0OWVmMDY5EAEYGSD///8HKghlMDQwYTI5MjIG5omT6Zu3OOjQ5uaQMUjhhsHj+P////8BYgCKAQCaARAKCEE3REFDQ0Q3EIrg+6QGogFXEgbmipgqKioiL2h0dHBzOi8vaTAuaGRzbGIuY29tL2Jmcy9mYWNlL21lbWJlci9ub2ZhY2UuanBnOJBOQAFaAggBYg0Qlq3aBBoGPjUwMDAwagByAHoAqgEFGKLlrAw='
}

**Comment by leonard2z** [comment]
![image](https://github.com/simon300000/bilibili-live-ws/assets/37145130/42261b11-c8c8-494c-8c6a-91171a3c77f7)

**Comment by leonard2z** [comment]
pull 之后解决了~ 感谢大佬！

**Comment by simon300000** [comment]
啊呀 我啥也没做呀

**Comment by simon300000** [comment]
关于用户名变成星号，可以参考这个 #397

至于dm_v2 似乎是个protobuf
https://github.com/xfgryujk/blivedm/pull/30
