### ISSUE TITLE
上舰长会报错

### ISSUE THREAD

**Issue by xcstream** [simon300000/bilibili-live-ws#4]
舰长消息变了
上舰长会报错

TypeError: Cannot read property 'includes' of undefined
  at LiveWS.<anonymous> (     /bilibili-live-ws/src/index.js:38:33)
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by simon300000** [comment]
你好，谢谢反馈！

这个问题应该已经在 https://github.com/simon300000/bilibili-live-ws/commit/180ef0e4a56e9e829a38ab2d2d01b326627e39eb 修复，请试试看最新的1.1.6版本

**Comment by simon300000** [comment]
新出的2.0.0版本支持TCP连接，欢迎试试！

**Comment by xcstream** [comment]
好的呢

**Comment by simon300000** [comment]
wua 问题修复了吗？

我把msg.cmd作为cmd的第二后选项了，导致出问题的似乎是这样一个包，cmd被放进msg了
<img width="808" alt="image" src="https://user-images.githubusercontent.com/12656264/68797100-37b74a80-0654-11ea-81d4-83831076efec.png">

**Comment by xcstream** [comment]
暂时没有问题， 继续观察中

**Comment by simon300000** [comment]
wua 这个问题大概修好了
