### ISSUE TITLE
需要登录能力

### ISSUE THREAD

**Issue by shuTwT** [simon300000/bilibili-live-ws#404]
游客模式弹幕用户名打码且漏弹幕
以下行为经过测试：
只传uid 不行
传入 uid,key 不行
传入 uid,buvid 不行
传入 uid,key,buvid 不行
传入 uid,key,buvid(host|address) 不行
protover 1 2 3 均不行

authbody该传什么？
能传cookie吗

**Comment by qiaoshouzi** [comment]
要在请求 `https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo` 获取 `key` 的时候带上Cookie

**Comment by simon300000** [comment]
authBody是给开放平台用的，带cookie之后用uid key和buvid应该就可以拿正常数据了
