### ISSUE TITLE
tcp的报错

### ISSUE THREAD

**Issue by xcstream** [simon300000/bilibili-live-ws#5]
![image](https://user-images.githubusercontent.com/895339/69003092-0b8f1880-0937-11ea-8c3f-685b8570f9c4.png)

**Comment by simon300000** [comment]
awww 我知道了

**Comment by xcstream** [comment]
粘包

**Comment by simon300000** [comment]
谢谢提醒，我试试看能不能解决

**Comment by simon300000** [comment]
我发了bilibili-live-ws@2.0.2
应该修复了这个问题，请试试看→_→！

**Comment by xcstream** [comment]
嗯呢 我更新一下

**Comment by simon300000** [comment]
wua 大概是修好了
