### ISSUE TITLE
有没有连接多个房间的方法=，=

### ISSUE THREAD

**Issue by lovezm** [simon300000/bilibili-live-ws#8]
dalao 比如我想连接两个房间 要怎样操作啊

**Comment by simon300000** [comment]
new 两个LiveWS啊

**Comment by lovezm** [comment]
我靠 那要是连接100个 不得new100个

**Comment by simon300000** [comment]
是
我有个服务连了600多个
可以看https://github.com/simon300000/bilibili-live-ws#benchmark-简单对比

如果真的很多的话，可以用TCP

**Comment by Billyzou0741326** [comment]
谢谢大佬的项目 

完成度比我的高好多... 感觉好多地方可以参考

**Comment by simon300000** [comment]
@Billyzou0741326 呀 不用谢
有问题随时问我哦！

**Comment by Billyzou0741326** [comment]
> @Billyzou0741326
> 呀 不用谢
> 有问题随便问我哦！
> (不是什么dalao)

hhh一定一定
